version: "3"
services:
  db:
    container_name: wiki-db
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: none
    ports:
      - "15432:5432"
  wiki:
    container_name: wiki-app
    image: ghcr.io/yaegashi/wiki
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wiki
      DB_USER: wikijs
      DB_PASS: wikijsrocks
    depends_on:
      - db
    ports:
      - "3000:3000"
